[default]
src = 'src'
out = 'out'
libs = ['lib']
remappings = ['@openzeppelin/=lib/openzeppelin-contracts/']
verbosity = 3
ffi = true
force = true
eth_rpc_url = 'https://moonriver.api.onfinality.io/public'


# See more config options https://github.com/gakonst/foundry/tree/master/config
